Fix x86 build when EFI is enabled
After enabling EFI, our x86 build failed:
drivers/firmware/efi/efi.c: In function 'efi_mem_reserve_persistent':
drivers/firmware/efi/efi.c:1024:40: error: 'SZ_4K' undeclared (first use in this function)
  rc = efi_mem_reserve_iomem(__pa(rsv), SZ_4K);
                                        ^~~~~
drivers/firmware/efi/efi.c:1024:40: note: each undeclared identifier is reported only once for each function it appears in

The offender is the backport of "efi/memreserve: Register reservations as 'reserved' in /proc/iomem". This was backported to make kexec work on 6g instances.

For 4.14 aarch64, linux/sizes.h is included through this chain:
In file included from ./arch/arm64/include/asm/memory.h:180:0,
                 from ./arch/arm64/include/asm/thread_info.h:30,
                 from ./include/linux/thread_info.h:38,
                 from ./include/asm-generic/preempt.h:5,
                 from ./arch/arm64/include/generated/asm/preempt.h:1,
                 from ./include/linux/preempt.h:81,
                 from ./include/linux/radix-tree.h:28,
                 from ./include/linux/idr.h:15,
                 from ./include/linux/kernfs.h:14,
                 from ./include/linux/sysfs.h:16,
                 from ./include/linux/kobject.h:21,
                 from drivers/firmware/efi/efi.c:20:

For 5.4 x86, this is how linux/sizes.h is included:
                 from ./include/linux/mm.h:29,
                 from ./include/linux/pid_namespace.h:7:0,
                 from ./include/linux/ptrace.h:10,
                 from ./include/uapi/linux/elfcore.h:8,
                 from ./include/linux/elfcore.h:10,
                 from ./include/linux/crash_core.h:6,
                 from ./include/linux/kexec.h:18,
                 from drivers/firmware/efi/efi.c:27:

It wasn't until 5.1, until "mm: refactor readahead defines in mm.h" was introduced, that <linux/sizes.h> was included in mm.h.

The offending, backported patch, "efi/memreserve: Register reservations as 'reserved' in /proc/iomem" was first included in 5.5.

Signed-off-by: Andy Strohman <astroh@amazon.com>